version: '3.1'

services:
  abei-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.mind-bricks.com/mind-bricks/abei-api
    restart: on-failure
    ports:
      - "8000:80"
    networks:
      - mb-back

networks:
  mb-back:
