# Generated by Django 2.2.8 on 2020-10-12 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRun',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('uuid', models.UUIDField(
                    default=uuid.uuid1, unique=True)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('running', 'Running'),
                        ('finished', 'Finished')
                    ],
                    default='pending',
                    max_length=16
                )),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('finished_time', models.DateTimeField(
                    default=None, null=True)),
                ('outputs', models.TextField(default=None, null=True)),
                ('errors', models.TextField(default=None, null=True)),
                ('procedure', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='runs',
                    to='editors.Procedure'
                )),
            ],
        ),
    ]
