# Generated by Django 2.2.8 on 2020-10-21 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('signature', models.CharField(
                    max_length=128
                )),
                ('docstring', models.TextField(
                    blank=True,
                    default=''
                )),
                ('editable', models.BooleanField(
                    default=True
                )),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureJoint',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('signature', models.CharField(
                    max_length=128
                )),
                ('inner_procedure', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='joint_references',
                    to='editors.Procedure'
                )),
                ('outer_procedure', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='joints',
                    to='editors.Procedure'
                )),
            ],
            options={
                'unique_together': {('outer_procedure', 'signature')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureOutput',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('signature', models.CharField(
                    max_length=128
                )),
                ('index', models.SmallIntegerField()),
                ('procedure', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='outputs',
                    to='editors.Procedure'
                )),
            ],
            options={
                'unique_together': {('procedure', 'index')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureSite',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('signature', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureSiteRelationship',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('base', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='base_relations',
                    to='editors.ProcedureSite'
                )),
                ('sub', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sub_relations',
                    to='editors.ProcedureSite'
                )),
            ],
            options={
                'unique_together': {('base', 'sub')},
            },
        ),
        migrations.AddField(
            model_name='proceduresite',
            name='base_sites',
            field=models.ManyToManyField(
                related_name='sub_sites',
                through='editors.ProcedureSiteRelationship',
                to='editors.ProcedureSite'
            ),
        ),
        migrations.AddField(
            model_name='proceduresite',
            name='user',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sites',
                to='users.User'
            ),
        ),
        migrations.CreateModel(
            name='ProcedureOutputLink',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('output_index', models.SmallIntegerField()),
                ('output', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='output_link',
                    to='editors.ProcedureOutput'
                )),
                ('output_joint', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='output_link',
                    to='editors.ProcedureJoint'
                )),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='site',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='procedures',
                to='editors.ProcedureSite'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='proceduresite',
            unique_together={('user', 'signature')},
        ),
        migrations.CreateModel(
            name='ProcedureJointLink',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('input_index', models.SmallIntegerField()),
                ('index', models.SmallIntegerField()),
                ('input_joint', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='link_references',
                    to='editors.ProcedureJoint'
                )),
                ('joint', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='links',
                    to='editors.ProcedureJoint'
                )),
            ],
            options={
                'unique_together': {('joint', 'index')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureInput',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('signature', models.CharField(max_length=128)),
                ('index', models.SmallIntegerField()),
                ('procedure', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='inputs',
                    to='editors.Procedure'
                )),
            ],
            options={
                'unique_together': {('procedure', 'index')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('site', 'signature')},
        ),
    ]
