# Generated by Django 2.2.8 on 2020-10-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresite',
            name='user',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sites',
                to='users.User'
            ),
        ),
        migrations.AlterField(
            model_name='proceduresite',
            name='signature',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='proceduresite',
            unique_together={('user', 'signature')},
        ),
    ]
