# Generated by Django 2.2.8 on 2020-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_auto_20201015_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
